name: TaylorGP
channels:
    - conda-forge
dependencies:
    - python=3.*
    - cmake>=3.18
    - scikit-learn
    - numpy
    - sympy
    - pandas
    - time
    - copy
    - itertools
    - timeout_decorator
    - scipy
    - joblib
    - numbers
    - itertools
    - abc
    - warnings
    - math
    - random
    - cython=0.29.*
    # - pip=20.*
    - pip
        - eigency==1.77
        - pmlb==1.*
